spring:
  application:
    name: bianpovisualization

influx:
  url: http://localhost:8086
  data_bucket: BianpoData
  map_bucket: BianpoMap
  token: 5__EkSeuhfUWfKR0mcZqbF_yuqPrl5r0IkgYF3GlEpQkg_Jry8u2uCm3CdE0kVbac6fw4sBMgEuwX-EdIGM9GA==
  org: fhzn

fhzn:
  username: 15691610692
  password: a15691610692
  token_url: http://xmnengjia.com/sdLamp/api/external/accessToken
  list_url: http://xmnengjia.com/sdLamp/api/external/deviceList
  update_url: http://xmnengjia.com/sdLamp/api/external/updateStatus
  get_url: http://xmnengjia.com/sdLamp/api/external/deviceStatus
